### office visitor management system
POST https://officevisitor.azurewebsites.net/register-staff
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZhZGgiLCJyb2xlIjoic2VjdXJpdHkiLCJpYXQiOjE3MDQwMzI2NDB9.gWOpeArs6ph8xr__H_Y3bNsAKBztV_b62eyD_4uF8rM

{
  "username": "bob",
  "password": "p4ss" 
}
// staff registration

###

POST https://officevisitor.azurewebsites.net/register-security
Content-Type: application/json

{
  "username": "alice",
  "password": "pass" 
}
// security registration

###

POST https://officevisitor.azurewebsites.net/login-staff
Content-Type: application/json

{
  "username": "bob",
  "password": "p4ss" 
}
// staff login

###

POST https://officevisitor.azurewebsites.net/login-security
Content-Type: application/json

{
  "username": "alice",
  "password": "pass" 
}
// security login

###

POST https://officevisitor.azurewebsites.net/appointments
Content-Type: application/json

{
  "name": "max",
  "company": "123 Corporation",
  "purpose": "meeting",
  "phoneNo": "011223344",
  "date": "2-1-2024",
  "time": "12:00PM",
  "verification": "N/A",
  "staff": {
    "username": "bob"
  }
}
// visitor's form to make appointment
###

GET https://officevisitor.azurewebsites.net/staff-appointments/bob
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvYiIsInJvbGUiOiJzdGFmZiIsImlhdCI6MTcwNDIwNzQ4N30.zhiaUv0j7gxRb_MRLToruUwp75Hqc0q3txtMESKK5XM
// list appointment (staff can check their own appointment)

###

PUT https://officevisitor.azurewebsites.net/appointments/max
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvYiIsInJvbGUiOiJzdGFmZiIsImlhdCI6MTcwNDIwNzQ4N30.zhiaUv0j7gxRb_MRLToruUwp75Hqc0q3txtMESKK5XM
Content-Type: application/json

{ "verification": "verified" }
// only staff can verified their own visitor
###

DELETE https://officevisitor.azurewebsites.net/appointments/yat
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZhZGgiLCJyb2xlIjoic3RhZmYiLCJpYXQiOjE2ODc2ODM1NDh9.XkbTmIIEl9YSoZfuEJJCuhwDln_PU9pLrOktBOdVsok
// only staff can delete their own appointment
###

###
GET https://officevisitor.azurewebsites.net/appointments?name=max
// visitor to view their apt
###
POST https://officevisitor.azurewebsites.net/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJvYiIsInJvbGUiOiJzdGFmZiIsImlhdCI6MTcwNDIwNzQ4N30.zhiaUv0j7gxRb_MRLToruUwp75Hqc0q3txtMESKK5XM
Content-Type: application/json

{
  "username": "bob"
}